// Hino Connect GPS adapter — logs into the Hino Connect account via AWS
// Cognito's HOSTED UI (a Cognito-managed login form, OAuth2 implicit grant)
// and fetches the live vehicle cluster map.
//
// This is NOT a direct Cognito API login (InitiateAuth/SRP) — that was this
// file's original design, but it turned out the Hino Connect app client only
// has the Hosted UI flow enabled (confirmed by reading the live app's own
// public config.js, which only exposes a getLoginHostedPage() URL, never an
// API-based auth flow). Any correct username/password fails with
// NotAuthorizedException via the direct-API approach, because that auth flow
// itself isn't permitted for this client — so the fix is to drive the same
// hosted login FORM the browser uses, the same way solofleet.ts already
// drives SoloFleet's ASP.NET login form.
//
// Login flow (confirmed live by re-running Discovery after the original
// SRP-based login kept failing with correct credentials):
//   1. GET  https://gazelle-ap-southeast-1-sg-hino-idp.auth.ap-southeast-1.amazoncognito.com/login
//           ?client_id=<CLIENT_ID>&response_type=token&redirect_uri=<REDIRECT_URI>
//      -> capture Set-Cookie + parse the hidden _csrf value from the form.
//   2. POST the same URL -> _csrf/username/password/cognitoAsfData/signInSubmitButton,
//      with step 1's cookies forwarded; redirect is NOT followed so we can
//      read the final Location header, which (on success) is <REDIRECT_URI>
//      with `#access_token=...` in the fragment (implicit grant — the token
//      is never in the response body, only that header).
//      cognitoAsfData is AWS's client-side bot/fingerprint payload, normally
//      generated by JS in a real browser — sent empty here since there is no
//      browser to generate it. Cognito's Advanced Security Features (if
//      enabled on this user pool) may still challenge/flag a login without
//      it; that would surface as a distinct failure, not a silent success.
//   3. POST /mapproxy/map/clusters with `Authorization: Bearer <token>` and a
//      fixed Indonesia-wide bounding box; flatten every returned cluster's
//      devices[] into one array.

import { AppError } from "@/lib/action-result";
import { resolveGpsKredensial } from "@/lib/queries/gps-kendaraan-kredensial";
import type { NormalizedVehiclePosition, VehicleGpsProvider } from "@/lib/gps-providers/types";
import { normalizeToUtc } from "@/lib/gps-providers/types";

// Identifies the Hino Connect application itself (not per-customer values) —
// confirmed live via Discovery.
const CLIENT_ID = "keguk4gegt09c9kmfa5rvb1b8";
const HOSTED_UI_BASE = "https://gazelle-ap-southeast-1-sg-hino-idp.auth.ap-southeast-1.amazoncognito.com";
// Must match a callback URL registered on the Cognito app client — confirmed
// live as the real app's own post-login landing route.
const REDIRECT_URI = "https://connect.hino.co.id/app/auth/success-login";
const LOGIN_URL = `${HOSTED_UI_BASE}/login?client_id=${CLIENT_ID}&response_type=token&redirect_uri=${encodeURIComponent(REDIRECT_URI)}`;

const CLUSTERS_URL = "https://be-pub-sg-hino.gazellecomputing.com/mapproxy/map/clusters";

// Same cookie-jar helpers as solofleet.ts — kept local rather than shared
// since each adapter's login flow is otherwise unrelated.
function extractSetCookies(response: Response): string[] {
  const headersWithGetSetCookie = response.headers as Headers & {
    getSetCookie?: () => string[];
  };
  if (typeof headersWithGetSetCookie.getSetCookie === "function") {
    return headersWithGetSetCookie.getSetCookie();
  }
  const rawHeaders = response.headers as unknown as { raw?: () => Record<string, string[]> };
  if (typeof rawHeaders.raw === "function") {
    return rawHeaders.raw()["set-cookie"] ?? [];
  }
  const cookies: string[] = [];
  for (const [key, value] of response.headers.entries()) {
    if (key.toLowerCase() === "set-cookie") cookies.push(value);
  }
  return cookies;
}

function cookiesToHeader(setCookieHeaders: string[]): string {
  return setCookieHeaders
    .map((cookie) => cookie.split(";")[0].trim())
    .filter(Boolean)
    .join("; ");
}

// Cognito's Hosted UI login page renders the sign-in form's hidden fields
// twice (a duplicated markup block in its template) — both copies carry the
// same value, so the first match is fine.
function extractCsrfToken(html: string): string | null {
  const match = html.match(/<input[^>]+name=["']_csrf["'][^>]+value=["']([^"']+)["']/i);
  return match ? match[1] : null;
}

// Fixed Indonesia-wide bounding box from the spec. The bounding box fields
// MUST be nested under `boundingBox` — sending them flat at the root (this
// file's original shape) passes Cognito auth fine but makes the backend
// itself 500 on every request, silently, with no useful error body. Only
// caught once a real login (see this file's header comment) finally reached
// this call for the first time.
const CLUSTERS_REQUEST_BODY = {
  boundingBox: {
    topLeftCorner: { lon: 103.0977934375, lat: -1.9072132966240953 },
    bottomRightCorner: { lon: 114.89710984375, lat: -11.798864459079624 },
  },
  fleets: [] as string[],
  // The original plan raised this from Discovery's captured 25 to 500 "so a
  // growing fleet doesn't silently get truncated" — but the backend crashes
  // (500, no useful error body) above some undocumented cap: confirmed live
  // that 500 and 250 both fail while 100 succeeds. 100 is still comfortably
  // above this account's current 4 vehicles; if the fleet ever approaches
  // that, re-verify the real cap live before raising it further rather than
  // guessing at a new value.
  deviceListMaxLen: 100,
  zoomLevel: 7,
  hideExpired: true,
};

interface HinoVehicleLastInfo {
  vehicleState: string;
  lastTransmissionTimestamp: string;
  deviceId: string;
  vehicleId: string;
  latitude_deg: number;
  longitude_deg: number;
  altitude_m: number;
  heading_deg: number;
  speed_kmh: number;
  engineHours_s: number;
  distance_m: number;
}

interface HinoDevice {
  vehicleId: string;
  deviceId: string;
  name: string;
  plate: string;
  vin: string;
  type: string;
  unreadAlarms: boolean;
  vehicleLastInfo: HinoVehicleLastInfo;
  position: { lat: number; lon: number; geohash: string; fragment: boolean };
  [key: string]: unknown;
}

interface HinoCluster {
  geoHash: string;
  size: number;
  devices: HinoDevice[];
  clusterCenter: { lat: number; lon: number; geohash: string; fragment: boolean };
}

interface HinoClustersResponse {
  status: boolean;
  statusCode: number;
  message: string;
  error: string;
  data: HinoCluster[];
  status_code: number;
}

/**
 * Logs into Hino Connect via its Cognito Hosted UI login form (the only auth
 * flow this app client actually supports — see this file's header comment)
 * and returns the access token from the implicit-grant redirect's URL
 * fragment. Throws AppError on any failure (missing credentials or a
 * rejected login), never logging the password.
 */
async function login(perusahaanId: number): Promise<string> {
  const kredensial = await resolveGpsKredensial(perusahaanId, "hino");
  if (!kredensial) {
    throw new AppError("Kredensial GPS Hino Connect belum dikonfigurasi.");
  }

  // Step 1: GET the hosted login page to obtain the session cookie + _csrf token.
  const getResponse = await fetch(LOGIN_URL, { method: "GET" });
  if (!getResponse.ok) {
    throw new AppError(`Gagal membuka halaman login Hino Connect (status ${getResponse.status}).`);
  }
  const loginPageHtml = await getResponse.text();
  const getCookieHeader = cookiesToHeader(extractSetCookies(getResponse));
  const csrfToken = extractCsrfToken(loginPageHtml);
  if (!csrfToken) {
    throw new AppError(
      "Tidak dapat menemukan _csrf pada halaman login Hino Connect — kemungkinan struktur halaman berubah."
    );
  }

  // Step 2: POST the credentials, with the session cookie forwarded.
  // redirect: "manual" so we can read the POST's own Location header — on
  // success it's REDIRECT_URI with `#access_token=...` in the fragment,
  // which fetch would otherwise silently follow and lose.
  const body = new URLSearchParams({
    _csrf: csrfToken,
    username: kredensial.username,
    password: kredensial.password,
    cognitoAsfData: "",
    signInSubmitButton: "signInSubmitButton",
  });
  const postResponse = await fetch(LOGIN_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      Cookie: getCookieHeader,
    },
    body: body.toString(),
    redirect: "manual",
  });

  const isRedirect = postResponse.status >= 300 && postResponse.status < 400;
  const location = postResponse.headers.get("location") ?? "";
  if (!isRedirect || !location.startsWith(REDIRECT_URI)) {
    throw new AppError(
      `Login Hino Connect gagal (status ${postResponse.status}) — periksa username/password kredensial.`
    );
  }

  const fragment = location.slice(location.indexOf("#") + 1);
  const accessToken = new URLSearchParams(fragment).get("access_token");
  if (!accessToken) {
    throw new AppError(
      "Login Hino Connect berhasil redirect tapi access_token tidak ditemukan pada URL — kemungkinan Cognito meminta langkah keamanan tambahan (mis. verifikasi perangkat baru)."
    );
  }

  return accessToken;
}

async function fetchPositions(perusahaanId: number): Promise<NormalizedVehiclePosition[]> {
  const accessToken = await login(perusahaanId);

  const response = await fetch(CLUSTERS_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      // Required — without it this endpoint specifically (unlike the other
      // Hino Connect endpoints this adapter/Discovery tried, which all work
      // fine without it) 500s on every request.
      Accept: "application/json",
      Authorization: `Bearer ${accessToken}`,
    },
    body: JSON.stringify(CLUSTERS_REQUEST_BODY),
  });
  if (!response.ok) {
    throw new AppError(`Gagal mengambil data kendaraan Hino Connect (status ${response.status}).`);
  }

  const payload = (await response.json()) as HinoClustersResponse;
  if (!payload.status) {
    throw new AppError(`Respons Hino Connect menandakan gagal: ${payload.message || payload.error}`);
  }

  const clusters = payload.data ?? [];
  const devices = clusters.flatMap((cluster) => cluster.devices ?? []);

  const positions: NormalizedVehiclePosition[] = [];
  for (const d of devices) {
    try {
      // Some devices genuinely have no plate registered in Hino Connect yet
      // (it falls back to showing the VIN as a placeholder) — per the user,
      // these are real vehicles without a plate assigned, not junk data, so
      // they're included as-is. Nothing to normalizePlate()-match against a
      // real Armada plate, so armada-gps.ts's existing unmatched-device
      // handling naturally shows them with a "Belum terhubung ke Armada"
      // badge, same as any other unmatched device.
      positions.push({
        provider: "hino",
        externalVehicleId: d.vehicleId,
        plateRaw: d.plate,
        latitude: d.vehicleLastInfo.latitude_deg,
        longitude: d.vehicleLastInfo.longitude_deg,
        speedKmh: d.vehicleLastInfo.speed_kmh,
        heading: d.vehicleLastInfo.heading_deg,
        // Hino's payload has no reliable ignition boolean — only the coarser
        // vehicleState (MOVING/IDLE/OFF) — so leave null rather than guessing.
        ignitionOn: null,
        recordedAtUtc: normalizeToUtc(d.vehicleLastInfo.lastTransmissionTimestamp),
        rawPayload: d,
      });
    } catch (err) {
      // One malformed device (missing vehicleLastInfo, bad timestamp, etc.)
      // shouldn't zero out the whole provider's sync cycle — skip it and
      // keep processing the rest.
      console.warn(
        `[hino-connect] Melewati device (vehicleId=${d?.vehicleId ?? "unknown"}) karena gagal dipetakan:`,
        err instanceof Error ? err.message : err
      );
    }
  }
  return positions;
}

export const hinoConnectProvider: VehicleGpsProvider = {
  provider: "hino",
  fetchPositions,
};
